trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Terraform install
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Terraform INIT
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'saurabh-connection'
    backendAzureRmResourceGroupName: 'saurabh'
    backendAzureRmStorageAccountName: 'vmstorage00710'
    backendAzureRmContainerName: 'vminfra'
    backendAzureRmKey: 'pak.terraform.tfstate'

# Terraform PLAN
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'saurabh-connection'

# Terraform APPLY
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'saurabh-connection'
