trigger:
- main

pool:
 super pool

variables:
  TF_DIR: dev

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(TF_DIR)'
    backendServiceArm: 'saurabhsconnection'
    backendAzureRmResourceGroupName: 'frontrg123'
    backendAzureRmStorageAccountName: 'vmstorage00710'
    backendAzureRmContainerName: 'vminerconta'
    backendAzureRmKey: 'pak.terraform.tfstate'

# - task: TerraformTaskV4@4
#   displayName: Terraform Plan
#   inputs:
#     provider: 'azurerm'
#     command: 'plan'
#     workingDirectory: '$(TF_DIR)'
#     environmentServiceNameAzureRM: 'saurabhsconnection'

# - task: TerraformTaskV4@4
#   displayName: Terraform Apply
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     workingDirectory: '$(TF_DIR)'
#     environmentServiceNameAzureRM: 'saurabhsconnection'
#     args: '-auto-approve'
