trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'

- script: |
    terraform --version
    terraform init
    terraform validate
    terraform plan
  displayName: 'Terraform Init Validate Plan'
