trigger:
- main

pool:
  name: super pool

variables:
  TF_DIR: dev

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(TF_DIR)'
    backendServiceArm: 'saurabhsconnection'
    backendAzureRmResourceGroupName: 'frontrg123'
    backendAzureRmStorageAccountName: 'vmstorage00710'
    backendAzureRmContainerName: 'vminerconta'
    backendAzureRmKey: 'pak.terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(TF_DIR)'
    environmentServiceNameAzureRM: 'saurabhsconnection'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(TF_DIR)'
    environmentServiceNameAzureRM: 'saurabhsconnection'
    args: '-auto-approve'
