trigger: none
pool: infrapool
stages:
- stage: initplanapply
  displayName: init plan apply
  jobs:
    - job: init
      displayName: terrform init
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/todoinfra/dev'
          backendServiceArm: 'yuvaconnection'
          backendAzureRmStorageAccountName: 'vmstorage1707'
          backendAzureRmContainerName: 'vminerconta'
          backendAzureRmKey: 'pak.terraform.tfstate'